services:
  usebox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}

    container_name: usebox-app
    ports:
      - "8050:80"

    restart: unless-stopped
